# Generated by Django 5.2.5 on 2025-08-11 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='status',
            field=models.CharField(choices=[('todo', 'ToDo'), ('doing', '進行中'), ('done', '完了')], db_index=True, default='todo', max_length=10, verbose_name='状態'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'ToDo'), ('doing', '進行中'), ('done', '完了')], db_index=True, default='todo', max_length=10, verbose_name='状態'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='completed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='完了'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='description',
            field=models.TextField(blank=True, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='期限'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='priority',
            field=models.IntegerField(choices=[(1, '低'), (2, '中'), (3, '高')], db_index=True, default=2, verbose_name='優先度'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='担当者'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='完了'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='期限'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, '低'), (2, '中'), (3, '高')], db_index=True, default=2, verbose_name='優先度'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='担当者'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'status', 'due_date'], name='todo_task_user_id_a5bbd1_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['completed', 'priority'], name='todo_task_complet_948165_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('priority__in', [1, 2, 3])), name='task_priority_valid'),
        ),
    ]
