# Generated by Django 5.2.5 on 2025-08-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_historicaltask_status_task_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='status',
            field=models.CharField(choices=[('todo', 'ToDo'), ('doing', '進行中'), ('done', '完了'), ('blocked', '保留')], db_index=True, default='todo', max_length=10, verbose_name='状態'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'ToDo'), ('doing', '進行中'), ('done', '完了'), ('blocked', '保留')], db_index=True, default='todo', max_length=10, verbose_name='状態'),
        ),
    ]
